#!/usr/bin/python3.5
import sys
from boto3 import session
from botocore.client import Config

ACCESS_ID = ''
SECRET_KEY = ''

# Initiate session
session = session.Session()
client = session.client('s3',
                        region_name='nyc3',
                        endpoint_url='https://nyc3.digitaloceanspaces.com',
                        aws_access_key_id=ACCESS_ID,
                        aws_secret_access_key=SECRET_KEY)

# Upload a file to your Space
if (len(sys.argv) < 3):
        raise Exception('Invalid number of arguments!')

bucket = sys.argv[1]
local = sys.argv[2]
remote = sys.argv[3]

client.upload_file(local, bucket, remote)
